version: '3.3'

services:
  myapp1:
    image: georgypzk/task4
    restart: always
    ports:
      - 81:80

  java-app:
    image: tomcat 
    restart: always
    ports:
      - 86:8080
    depends_on: 
      - db
  

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}

volumes:
  pgdata:  