[staging_ervers]
Vm2 ansible_host=20.125.97.204 ansible_user=azureuser ansible_ssh_private_key_file=/home/azureuser/SSH/Vm2_key.pem
Vm3 ansible_host=20.38.3.100 ansible_user=azureuser ansible_ssh_private_key_file=/home/azureuser/SSH/Vm3_key.pem