---
- name: Install docker
  hosts: all
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull Docker image
      docker_image:
        name: "georgypzk/lemp-stak-task5:v1"
        source: pull
    # Uncomment the following to enable insecure registries with Docker
    #- name: ensure docker can use insecure registries in 10.11.0.0/16
    #  lineinfile: "dest=/etc/default/docker regexp=^DOCKER_OPTS line=DOCKER_OPTS='--insecure-registry 10.11.0.0/16'"
        # Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Create containers
      docker_container:
        name: "georgypzk-lemp-stak-task5"
        image: "georgypzk/lemp-stak-task5:v1"
        state: present
      with_sequence: count=1

    #- name: deploy my LEMP docker container
    #  docker_container:
    #    image: georgypzk/lemp-stak-task5:v1
    #    name: lemp
    #    state: started
    #    auto_remove: true
    #    ports:
    #      - "8080:80"

    

    